-- Data fix: earlier room names were HTML-entity-encoded at write time (he.encode),
-- so accented names were stored corrupted, e.g. "Soirée" -> "Soir&eacute;e".
-- The encoder has been removed; this decodes existing rows back to plain text.
-- Only touches rows that still contain an entity ('&...;'), so it is idempotent.
-- Covers the French/European accent set + the core HTML chars he.encode emitted.
-- Ampersand is decoded LAST so chained entities resolve correctly.
UPDATE "Room"
SET "name" = REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(REPLACE("name", '&agrave;', 'à'), '&acirc;', 'â'), '&auml;', 'ä'), '&aacute;', 'á'), '&atilde;', 'ã'), '&egrave;', 'è'), '&eacute;', 'é'), '&ecirc;', 'ê'), '&euml;', 'ë'), '&igrave;', 'ì'), '&iacute;', 'í'), '&icirc;', 'î'), '&iuml;', 'ï'), '&ograve;', 'ò'), '&oacute;', 'ó'), '&ocirc;', 'ô'), '&ouml;', 'ö'), '&otilde;', 'õ'), '&ugrave;', 'ù'), '&uacute;', 'ú'), '&ucirc;', 'û'), '&uuml;', 'ü'), '&ccedil;', 'ç'), '&ntilde;', 'ñ'), '&yacute;', 'ý'), '&yuml;', 'ÿ'), '&oelig;', 'œ'), '&aelig;', 'æ'), '&szlig;', 'ß'), '&Agrave;', 'À'), '&Acirc;', 'Â'), '&Auml;', 'Ä'), '&Aacute;', 'Á'), '&Atilde;', 'Ã'), '&Egrave;', 'È'), '&Eacute;', 'É'), '&Ecirc;', 'Ê'), '&Euml;', 'Ë'), '&Igrave;', 'Ì'), '&Iacute;', 'Í'), '&Icirc;', 'Î'), '&Iuml;', 'Ï'), '&Ograve;', 'Ò'), '&Oacute;', 'Ó'), '&Ocirc;', 'Ô'), '&Ouml;', 'Ö'), '&Otilde;', 'Õ'), '&Ugrave;', 'Ù'), '&Uacute;', 'Ú'), '&Ucirc;', 'Û'), '&Uuml;', 'Ü'), '&Ccedil;', 'Ç'), '&Ntilde;', 'Ñ'), '&Yacute;', 'Ý'), '&Yuml;', 'Ÿ'), '&OElig;', 'Œ'), '&AElig;', 'Æ'), '&lt;', '<'), '&gt;', '>'), '&quot;', '"'), '&apos;', ''''), '&apos;', ''''), '&amp;', '&')
WHERE "name" LIKE '%&%;%';
